services:
  db:
    image: mysql:8.0
    container_name: my_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
     # PMA_USER: my_user
     # PMA_PASSWORD: my_password
    ports:
      - "8080:80"
    depends_on:
      - db

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_php
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: my_database
      DB_USER: my_user
      DB_PASS: my_password
      JWT_SECRET: diploma
      VITE_URL: beget

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - php

volumes:
  db_data:
